branches:
  only:
  - master
  - integration
language: node_js
node_js:
- '8'
services:
- mongodb
before_install:
- openssl aes-256-cbc -K $encrypted_b7d9be5f6c08_key -iv $encrypted_b7d9be5f6c08_iv
  -in ./backend/config/secrets.tar.enc -out ./backend/config/secrets.tar -d
- tar xvf ./backend/config/secrets.tar -C ./backend/config
before_script:
- cd backend
- npm install -g grunt-cli
- npm install
script: npm test -- --test
notifications:
  email: false
  slack:
    - secure: QqNqtaALiXR1skjaMMJ3R6Q4Tp/+ls/Ogq0Fi9XkRBUAUyTKF4HGNz15RDBxWX3Jm87bn1R3tEfk+bjt2hL0G5T9pPn+HOz+vpoT6ul17oRVjA8+pnd2NFOy01PdZ5zZCzea39aBrsQ0t1GLK7TRywT/8th8ojfUYceV1ItUm0TC0hRwKsQ7EjYyuZFTcpUwRjcoS2UOaEfLkTYSErSf8lNXgfHg7uko/69iXHbjTtqwug2GV/nMgpYX1/SvbiDWVKW0xBaDcAthK2HvErQagSgmvsESOX5wNbgsW45Fjm3KDSAt9ex0LAEddodg5E+musSDbswajIPBHNOWGIwkK7YoxHq9+gj1oCgUtLcz0DHTRKglR3JmI9rYrPiC1dd7eJh0xBFa4qNNdh5fFPVo0kXEgIZ+QsdtRNSsKeM0h7qlZjR8eMFRSziuQBGbN/1DHBEYmlMc/D/8iZaeck7VKpJvoNnDpqV21ObAwPkpANS7EOY5PLom+BhFzH5Z5koXU/Z8RFXHNZp6XbwaAn4Q++5VdObyrtvdrrPu6PGBHO7+kmAomhS65RfNGyEsn6Su0/mvPYAeofX+LsfM7g5/kecCkwtMlcZ63XU+B8OmJABLzaCPxZQBha3A4IsmBS1IwlMkTEuphmZ96DHuNead616+dYGZCDbj4/LWxaDw4Ww=
    - on_failure: always
