branches:
  only:
  - master
language: node_js
node_js:
- '8'
services:
- mongodb
before_install:
  openssl aes-256-cbc -K $encrypted_b7d9be5f6c08_key -iv $encrypted_b7d9be5f6c08_iv -in bugsnagSecret.json.enc -out bugsnagSecret.json -d
before_script:
- cd backend
- npm install -g grunt-cli
- npm install
script: npm test
notifications:
  email: false
  slack:
    secure: tRxnI7Tqk+36Im1RP1Hm0fXzK2tuOaJLqRw96OX0q40hmUE6Sv1OiamXb9+3VxB1HIXZS8/v+a/FVoR0TxCK61RpjA1+8zIQQR/CDuS8MS1xdNwr2vArIp8DYN+y/KHKab9zL7hFMW4J4wi6k8Id2W5p5raBQsSIDX+qj9jPwwyyKSOVxo5WesMDRPF5p75fBsjbqFSEWXYRxFASI+8l1Xzd3buej5qchBtlVGHkl/UP821tmrlO5/DznB8xRgn7AmsLnZMZe/GIToGATaIrPsm/6BsqR0zGC0vnVvuwB7dWH2O06KwIoz4Wj4DBaVvcJ+7kS1fa6r+YY/ncoM6pgxnjzV8rwhc/lQQLDVu55z3dPhVRhnnzazNJkqbXiI8bdDkq0e90QzegOTPExiOmrSLRycgtGZ04ObWnv6h1c46EynZ3OKaZLZ2tn4yjv/atCfJPPQWGhd8HTsLeK1HRrSt1ZmttEIU9DxOBkIUeV9palmituW3NUMnzlhtd1g/tW8QPGgddA/lxXZgf6NJ03A8weg9hcO1AEVFCbs1BMmDqPDIlKm56q+kShYiyWv1rjGGgDdHEv2oxORvLN2nUdWmaUfh/vdXCFaQgkccsFLcBIh+gt5ySk1O/A1NkIu5jH0AQR+WAmicAEQFH4TqH22CoDjyX8VAZclqXnsPmDgs=
    on_failure:always
    epicenter-group:3996sKrTuWBrxopQ24S6BZtG
